"""
BostonTech India CatalystScan — Organization-Specific .exe Builder
Generates customized CatalystScan executables with embedded org configuration.

HOW IT WORKS:
1. Admin enters org details (name, ID, telemetry URL, scan limit) in the dashboard
2. This module creates an org_config.json with those details
3. It copies the base CatalystScan.exe and bundles the config alongside it
4. The admin downloads a .zip containing the customized .exe + org_config.json
5. When the .exe runs, it loads the org_config.json to identify the organization

WHAT IS A DEVICE FINGERPRINT?
- A device fingerprint is a SHA-256 hash automatically generated by the .exe
- It is computed from: Motherboard Serial + CPU Processor ID + Primary Disk Serial
- These are hardware-level identifiers that DO NOT change when:
  * Windows is reinstalled
  * The .exe is deleted and re-downloaded
  * The user creates a new Windows account
- The fingerprint uniquely identifies a PHYSICAL MACHINE
- The user does NOT need to collect or enter anything — it's 100% automatic
"""

import os
import json
import shutil
import zipfile
import datetime
import hashlib
import secrets
import logging

logger = logging.getLogger(__name__)

# Import AGENT_API_KEY to embed in generated org configs
try:
    from config import AGENT_API_KEY
except ImportError:
    import os
    AGENT_API_KEY = os.environ.get("AGENT_API_KEY", "")


# Directories
SERVER_DIR = os.path.dirname(os.path.abspath(__file__))
UPLOADS_DIR = os.path.join(SERVER_DIR, "uploads")
OUTPUT_DIR = os.path.join(SERVER_DIR, "generated_builds")

# Ensure uploads directory exists
if not os.path.exists(UPLOADS_DIR):
    os.makedirs(UPLOADS_DIR)


def find_base_exe():
    """Locate the base CatalystScan.exe template."""
    search_paths = [
        # First priority: uploaded zip in the uploads folder (for --onedir builds)
        os.path.join(UPLOADS_DIR, "CatalystScan_base.zip"),
        # Second priority: uploaded exe
        os.path.join(UPLOADS_DIR, "CatalystScan.exe"),
        # Check generated_builds for CatalystScan_base.zip (Docker volume mount)
        os.path.join(OUTPUT_DIR, "CatalystScan_base.zip"),
        os.path.join(OUTPUT_DIR, "CatalystScan_base.exe"),
        # Fallback: same directory as server
        os.path.join(SERVER_DIR, "CatalystScan.exe"),
        # Fallback: parent directory
        os.path.join(SERVER_DIR, "..", "CatalystScan.exe"),
        # Fallback: Windows build directory
        os.path.join("C:\\ProgramData\\build_catalyst\\dist", "CatalystScan.exe"),
    ]
    valid_paths = [p for p in search_paths if os.path.exists(p)]
    
    if not valid_paths:
        # Last resort: find any .exe file in generated_builds (not a .zip)
        if os.path.exists(OUTPUT_DIR):
            for f in os.listdir(OUTPUT_DIR):
                if f.endswith(".exe"):
                    return os.path.join(OUTPUT_DIR, f)
        return None
        
    # Return the file that was most recently modified
    valid_paths.sort(key=lambda x: os.path.getmtime(x), reverse=True)
    return valid_paths[0]


def save_base_exe(file_bytes):
    """
    Save an uploaded CatalystScan.exe as the base template.
    Returns dict with success status and file info.
    """
    if not os.path.exists(UPLOADS_DIR):
        os.makedirs(UPLOADS_DIR)

    dest = os.path.join(UPLOADS_DIR, "CatalystScan.exe")
    with open(dest, "wb") as f:
        f.write(file_bytes)

    size_mb = round(os.path.getsize(dest) / (1024 * 1024), 2)
    return {
        "success": True,
        "path": dest,
        "size_mb": size_mb,
        "uploaded_at": datetime.datetime.now().isoformat(),
    }


def get_base_exe_info():
    """Check if the base .exe template exists and return its info."""
    path = find_base_exe()
    if path and os.path.exists(path):
        stat = os.stat(path)
        return {
            "exists": True,
            "path": path,
            "size_mb": round(stat.st_size / (1024 * 1024), 2),
            "modified": datetime.datetime.fromtimestamp(stat.st_mtime).isoformat(),
        }
    return {"exists": False}


def _generate_build_id(org_id):
    """Generate a unique SHA-256 build fingerprint."""
    raw = f"{org_id}:{datetime.datetime.now().isoformat()}:{secrets.token_hex(16)}"
    return hashlib.sha256(raw.encode()).hexdigest()


def generate_org_config(org_name, org_id, telemetry_url, scan_limit=2, extra=None, build_id=None, build_version=None, built_by=None):
    """Generate the org_config.json content with build metadata."""
    config = {
        "org_name": org_name,
        "org_id": org_id,
        "telemetry_url": telemetry_url,
        "default_scan_limit": scan_limit,
        "agent_api_key": AGENT_API_KEY,
        "generated_at": datetime.datetime.now().isoformat(),
    }
    if build_id:
        config["build_id"] = build_id
    if build_version:
        config["build_version"] = build_version
    if built_by:
        config["built_by"] = built_by
    if extra and isinstance(extra, dict):
        config.update(extra)
    return config


def build_org_exe(org_name, org_id, telemetry_url, scan_limit=2, built_by=None):
    """
    Build an organization-specific CatalystScan package.
    
    Returns a dict with:
    - success: bool
    - zip_path: path to the generated .zip file
    - build_id: unique SHA-256 fingerprint for the build
    - build_version: auto-incrementing version (e.g. 'v1', 'v2')
    - error: error message if failed
    """
    # Find base exe
    base_exe = find_base_exe()
    if not base_exe:
        return {
            "success": False,
            "error": "Base CatalystScan.exe not found. Please build it first using PyInstaller.",
        }

    # Create output directory
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    # Generate build versioning
    build_id = _generate_build_id(org_id)
    
    # Get next version from DB
    try:
        import database as db
        build_version = db.get_next_build_version(org_id)
    except Exception:
        build_version = "v1"

    # Sanitize org name for filename
    safe_name = "".join(c if c.isalnum() or c in "-_ " else "" for c in org_name).strip()
    safe_name = safe_name.replace(" ", "_")
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    
    build_name = f"CatalystScan_{safe_name}_{build_version}_{timestamp}"
    build_dir = os.path.join(OUTPUT_DIR, build_name)
    
    try:
        # Delete any older builds for this organization to prevent duplicates
        prefix = f"CatalystScan_{safe_name}_"
        for old_file in os.listdir(OUTPUT_DIR):
            if old_file.startswith(prefix) and old_file.endswith(".zip"):
                try:
                    os.remove(os.path.join(OUTPUT_DIR, old_file))
                except OSError:
                    pass

        # Create build directory
        os.makedirs(build_dir, exist_ok=True)

        # Generate org_config.json with build metadata
        config = generate_org_config(org_name, org_id, telemetry_url, scan_limit,
                                     build_id=build_id, build_version=build_version, built_by=built_by)
        config_path = os.path.join(build_dir, "org_config.json")
        with open(config_path, "w") as f:
            json.dump(config, f, indent=2)

        # Copy or extract the base build
        if base_exe.endswith(".zip"):
            with zipfile.ZipFile(base_exe, 'r') as zip_ref:
                zip_ref.extractall(build_dir)
        else:
            exe_dest = os.path.join(build_dir, "CatalystScan.exe")
            shutil.copy2(base_exe, exe_dest)

        # Create a README for the org
        readme_path = os.path.join(build_dir, "README.txt")
        with open(readme_path, "w") as f:
            f.write(f"BostonTech India — CatalystScan Hardware Assessment & Asset Protection\n")
            f.write(f"MSME Registered Enterprise | Salem, Tamil Nadu, India\n")
            f.write(f"{'='*60}\n\n")
            f.write(f"Organization: {org_name}\n")
            f.write(f"Build Date:   {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")
            f.write(f"QUICK START (GUI Mode):\n")
            f.write(f"1. Place both CatalystScan.exe and org_config.json in the SAME folder\n")
            f.write(f"2. Run CatalystScan.exe\n")
            f.write(f"3. The application will open in your browser at http://localhost:8000\n")
            f.write(f"4. Click 'Run Scan' to perform a hardware assessment\n")
            f.write(f"5. Download the PDF report when complete\n\n")
            f.write(f"BACKGROUND AGENT (Headless — Auto-Starts on Boot):\n")
            f.write(f"  Option A — With Admin rights (IT-managed):\n")
            f.write(f"    Open CMD as Admin, navigate to the folder, and run:\n")
            f.write(f"      CatalystScan.exe --install\n\n")
            f.write(f"  Option B — Without Admin (AD/Production laptops):\n")
            f.write(f"    Just double-click or run:\n")
            f.write(f"      CatalystScan.exe --install\n")
            f.write(f"    (Auto-detects non-admin and uses Windows Startup folder)\n\n")
            f.write(f"  To remove the agent:\n")
            f.write(f"      CatalystScan.exe --uninstall\n\n")
            f.write(f"  To check agent status:\n")
            f.write(f"      CatalystScan.exe --status\n\n")
            f.write(f"WHAT THE AGENT DOES AUTOMATICALLY:\n")
            f.write(f"- Sends heartbeat every 5 min (keeps device Online in dashboard)\n")
            f.write(f"- Runs tamper check every 30 min (detects hardware swaps)\n")
            f.write(f"- Full hardware scan every 24 hours (updates dashboard data)\n")
            f.write(f"- Syncs pending reports every 15 min\n\n")
            f.write(f"ANTI-THEFT PROTECTION:\n")
            f.write(f"- On first run, a hardware baseline is captured\n")
            f.write(f"- If any component (RAM, disk, GPU) is swapped, an alert is sent\n")
            f.write(f"- The central dashboard shows which components were changed\n\n")
            f.write(f"Server: {telemetry_url}\n")
            f.write(f"Support: contact@bostontech.in\n")

        # Create .zip package
        zip_filename = f"{build_name}.zip"
        zip_path = os.path.join(OUTPUT_DIR, zip_filename)
        
        with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
            for root, _, files in os.walk(build_dir):
                for file_name in files:
                    file_path = os.path.join(root, file_name)
                    arcname = os.path.join(build_name, os.path.relpath(file_path, build_dir))
                    zf.write(file_path, arcname)

        # Cleanup the temp build directory
        shutil.rmtree(build_dir)

        # Register build in DB
        try:
            import database as db
            db.register_build(build_id, build_version, org_id, org_name, built_by, scan_limit, zip_filename)
        except Exception as reg_err:
            logger.warning(f"Could not register build in DB: {reg_err}")

        return {
            "success": True,
            "zip_path": zip_path,
            "zip_filename": zip_filename,
            "org_name": org_name,
            "org_id": org_id,
            "build_id": build_id,
            "build_version": build_version,
            "config": config,
        }

    except Exception as e:
        # Cleanup on error
        if os.path.exists(build_dir):
            shutil.rmtree(build_dir)
        return {
            "success": False,
            "error": str(e),
        }


def list_generated_builds():
    """List all previously generated .zip builds."""
    if not os.path.exists(OUTPUT_DIR):
        return []
    
    builds = []
    for f in os.listdir(OUTPUT_DIR):
        if f.endswith(".zip"):
            path = os.path.join(OUTPUT_DIR, f)
            stat = os.stat(path)
            builds.append({
                "filename": f,
                "size_mb": round(stat.st_size / (1024 * 1024), 2),
                "created": datetime.datetime.fromtimestamp(stat.st_ctime).isoformat(),
            })
    
    builds.sort(key=lambda x: x["created"], reverse=True)
    return builds


def delete_build(filename):
    """Delete a generated build."""
    filename = os.path.basename(filename)
    path = os.path.join(OUTPUT_DIR, filename)
    if os.path.exists(path):
        os.remove(path)
        return True
    return False
